import type { Dataset } from "./DatasetCard";

export const datasets: Dataset[] = [
  {
    id: "1",
    name: "GPT-4 Fine-tuning Corpus",
    description: "Curated high-quality instruction-following dataset optimized for LLM fine-tuning with diverse task coverage.",
    category: "AI Training",
    price: "45",
    rentPrice: "2.5",
    size: "12.4 GB",
    format: "JSONL",
    downloads: 1284,
    expiresIn: "89 days",
    seller: "0x8a...f21e",
    verified: true,
    tags: ["NLP", "Instructions", "Multi-task"],
  },
  {
    id: "2",
    name: "DeFi Protocol Analytics",
    description: "Real-time aggregated data from 50+ DeFi protocols across Ethereum, Solana, and Sui ecosystems.",
    category: "Financial",
    price: "120",
    rentPrice: "8",
    size: "34.7 GB",
    format: "Parquet",
    downloads: 892,
    expiresIn: "142 days",
    seller: "0x3c...91ab",
    verified: true,
    tags: ["DeFi", "Cross-chain", "Real-time"],
  },
  {
    id: "3",
    name: "Satellite Imagery Dataset",
    description: "High-resolution satellite imagery covering urban areas with labeled land-use classification data.",
    category: "Geospatial",
    price: "200",
    size: "156 GB",
    format: "GeoTIFF",
    downloads: 445,
    expiresIn: "210 days",
    seller: "0x5d...c8f3",
    verified: true,
    tags: ["Satellite", "Urban", "Classification"],
  },
  {
    id: "4",
    name: "IoT Sensor Streams",
    description: "Industrial IoT sensor data from smart manufacturing facilities with anomaly detection labels.",
    category: "IoT",
    price: "30",
    rentPrice: "1.5",
    size: "8.2 GB",
    format: "CSV",
    downloads: 673,
    expiresIn: "45 days",
    seller: "0x9e...42dd",
    verified: false,
    tags: ["Sensors", "Manufacturing", "Anomaly"],
  },
  {
    id: "5",
    name: "Clinical Trial Results v3",
    description: "Anonymized clinical trial outcomes dataset covering 200+ trials across oncology and cardiology.",
    category: "Healthcare",
    price: "350",
    size: "22.1 GB",
    format: "FHIR JSON",
    downloads: 234,
    expiresIn: "300 days",
    seller: "0x1f...b7c4",
    verified: true,
    tags: ["Clinical", "Anonymized", "Oncology"],
  },
  {
    id: "6",
    name: "Social Sentiment Firehose",
    description: "Real-time sentiment analysis data from major social platforms with entity extraction and topic modeling.",
    category: "Social",
    price: "65",
    rentPrice: "4",
    size: "5.6 GB",
    format: "JSON",
    downloads: 1567,
    expiresIn: "60 days",
    seller: "0x7b...e915",
    verified: true,
    tags: ["Sentiment", "NLP", "Real-time"],
  },
  {
    id: "7",
    name: "Code Generation Pairs",
    description: "250K+ natural language to code pairs across Python, Rust, and TypeScript with test cases included.",
    category: "AI Training",
    price: "80",
    rentPrice: "5",
    size: "4.8 GB",
    format: "JSONL",
    downloads: 2103,
    expiresIn: "120 days",
    seller: "0x4a...d2f8",
    verified: true,
    tags: ["Code", "Multi-language", "Tested"],
  },
  {
    id: "8",
    name: "On-chain Transaction Graph",
    description: "Complete transaction graph data for Sui mainnet with wallet clustering and flow analysis.",
    category: "Financial",
    price: "95",
    rentPrice: "6",
    size: "78.3 GB",
    format: "GraphML",
    downloads: 521,
    expiresIn: "180 days",
    seller: "0x2e...a6c1",
    verified: true,
    tags: ["Sui", "Graph", "Wallets"],
  },
];

export const stats = [
  { label: "Datasets Listed", value: "12,847" },
  { label: "Total Volume", value: "2.4M SUI" },
  { label: "Active Agents", value: "8,234" },
  { label: "Avg. Uptime", value: "99.97%" },
];

export const categories = [
  "All",
  "AI Training",
  "Financial",
  "Healthcare",
  "Geospatial",
  "Social",
  "IoT",
];
